import { useState, useRef } from "react";
import { buildGenerate } from "@/lib/api";
import CodeOutput from "@/components/CodeOutput";
import ModelSelector from "@/components/ModelSelector";
import {
  Hammer,
  Play,
  Loader2,
  FileCode,
  Layers,
  Plus,
  X,
  FolderGit2,
  FileText,
  Paperclip,
  Download,
  Copy,
  Check,
  Upload,
} from "lucide-react";

interface AttachedFile {
  id: string;
  name: string;
  type: "file" | "repo" | "snippet";
  content: string;
}

export default function BuildPhase() {
  const [planStep, setPlanStep] = useState("");
  const [techStack, setTechStack] = useState("");
  const [filePath, setFilePath] = useState("");
  const [selectedModel, setSelectedModel] = useState("gpt-4o-mini");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState("");
  const [attachedFiles, setAttachedFiles] = useState<AttachedFile[]>([]);
  const [showAddPanel, setShowAddPanel] = useState(false);
  const [newFileName, setNewFileName] = useState("");
  const [newFileContent, setNewFileContent] = useState("");
  const [newFileType, setNewFileType] = useState<"file" | "repo" | "snippet">("file");
  const [copied, setCopied] = useState(false);
  const [generatedFiles, setGeneratedFiles] = useState<any[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleGenerate = async () => {
    if (!planStep.trim()) return;
    setLoading(true);
    setError("");
    setResult(null);
    try {
      const contextParts: string[] = [];
      if (attachedFiles.length > 0) {
        contextParts.push(
          "Referenced files:\n" +
            attachedFiles
              .map((f) => `--- ${f.name} (${f.type}) ---\n${f.content}`)
              .join("\n\n")
        );
      }
      const projectContext = contextParts.length > 0 ? contextParts.join("\n") : undefined;
      const res = await buildGenerate(planStep, techStack || undefined, projectContext, filePath || undefined);
      setResult(res);
      if (res.generated_code) {
        setGeneratedFiles((prev) => [
          ...prev,
          {
            file_path: res.file_path || filePath || `generated_${prev.length + 1}.${res.language || "ts"}`,
            code: res.generated_code,
            language: res.language,
            explanation: res.explanation,
            tokens: res.tokens_used,
            model: res.model,
          },
        ]);
      }
    } catch (e: any) {
      setError(e.message || "Failed to generate code");
    } finally {
      setLoading(false);
    }
  };

  const handleAddFile = () => {
    if (!newFileName.trim() || !newFileContent.trim()) return;
    const file: AttachedFile = {
      id: Date.now().toString(),
      name: newFileName.trim(),
      type: newFileType,
      content: newFileContent.trim(),
    };
    setAttachedFiles((prev) => [...prev, file]);
    setNewFileName("");
    setNewFileContent("");
    setShowAddPanel(false);
  };

  const handleBrowseFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;
    Array.from(files).forEach((file) => {
      const reader = new FileReader();
      reader.onload = (ev) => {
        const content = ev.target?.result as string;
        setAttachedFiles((prev) => [
          ...prev,
          { id: `${Date.now()}-${file.name}`, name: file.name, type: "file", content },
        ]);
      };
      reader.readAsText(file);
    });
    e.target.value = "";
  };

  const handleRemoveFile = (id: string) => {
    setAttachedFiles((prev) => prev.filter((f) => f.id !== id));
  };

  const handleCopyAll = async () => {
    const allCode = generatedFiles.map((f) => `// ${f.file_path}\n${f.code}`).join("\n\n");
    await navigator.clipboard.writeText(allCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadAll = () => {
    const allCode = generatedFiles
      .map((f) => `// File: ${f.file_path}\n// Generated by ZECT Build Phase (${f.model})\n\n${f.code}`)
      .join("\n\n" + "=".repeat(80) + "\n\n");
    const blob = new Blob([allCode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "zect-generated-code.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-amber-100 rounded-xl">
            <Hammer className="h-6 w-6 text-amber-600" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-slate-900">Build Phase</h1>
            <p className="text-slate-500">Generate production-ready code from plan steps using AI</p>
          </div>
        </div>
        {generatedFiles.length > 0 && (
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500">{generatedFiles.length} file(s) generated</span>
            <button onClick={handleCopyAll} className="p-2 text-slate-500 hover:text-blue-600 rounded-lg hover:bg-blue-50" title="Copy all code">
              {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
            </button>
            <button onClick={handleDownloadAll} className="p-2 text-slate-500 hover:text-blue-600 rounded-lg hover:bg-blue-50" title="Download all">
              <Download className="h-4 w-4" />
            </button>
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Panel — Input & Output */}
        <div className="lg:col-span-2 space-y-4">
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm">
            <div className="p-5 space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">
                  Plan Step / Feature Description *
                </label>
                <textarea
                  value={planStep}
                  onChange={(e) => setPlanStep(e.target.value)}
                  placeholder="e.g., Create a REST API endpoint for user authentication with JWT tokens, input validation, and rate limiting"
                  className="w-full h-32 p-3 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-amber-500 focus:border-amber-500 resize-none"
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    <Layers className="inline h-4 w-4 mr-1" />
                    Tech Stack (optional)
                  </label>
                  <input
                    type="text"
                    value={techStack}
                    onChange={(e) => setTechStack(e.target.value)}
                    placeholder="e.g., TypeScript, React, FastAPI, PostgreSQL"
                    className="w-full p-2.5 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-amber-500 focus:border-amber-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    <FileCode className="inline h-4 w-4 mr-1" />
                    Target File Path (optional)
                  </label>
                  <input
                    type="text"
                    value={filePath}
                    onChange={(e) => setFilePath(e.target.value)}
                    placeholder="e.g., src/api/auth.ts"
                    className="w-full p-2.5 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-amber-500 focus:border-amber-500"
                  />
                </div>
              </div>

              <ModelSelector value={selectedModel} onChange={setSelectedModel} />

              <button
                onClick={handleGenerate}
                disabled={loading || !planStep.trim()}
                className="flex items-center gap-2 px-5 py-2.5 bg-amber-600 hover:bg-amber-700 disabled:bg-slate-300 text-white rounded-lg font-medium transition"
              >
                {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}
                {loading ? "Generating..." : "Generate Code"}
              </button>
            </div>
          </div>

          {/* Error */}
          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700 text-sm">{error}</div>
          )}

          {/* Generated Code Result */}
          {result && (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5">
              <div className="flex items-center justify-between mb-3">
                <h2 className="text-lg font-semibold text-slate-900">Generated Code</h2>
                <div className="flex items-center gap-3 text-xs text-slate-500">
                  <span className="px-2 py-1 bg-slate-100 rounded">{result.language}</span>
                  <span>{result.tokens_used} tokens</span>
                  <span className="text-slate-400">via {result.model}</span>
                </div>
              </div>
              {result.file_path && (
                <p className="text-sm text-slate-600 mb-2">
                  <FileCode className="inline h-4 w-4 mr-1" />
                  {result.file_path}
                </p>
              )}
              {result.explanation && (
                <p className="text-sm text-slate-600 mb-3 bg-blue-50 p-3 rounded-lg">{result.explanation}</p>
              )}
              <CodeOutput
                code={result.generated_code}
                language={result.language}
                title={result.file_path || result.language}
                maxHeight="500px"
              />
            </div>
          )}
        </div>

        {/* Right Panel — Files & Context */}
        <div className="space-y-4">
          {/* Attached Files Panel */}
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm">
            <div className="p-4 border-b border-slate-100 flex items-center justify-between">
              <h3 className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                <Paperclip className="h-4 w-4" />
                Context Files ({attachedFiles.length})
              </h3>
              <button
                onClick={() => setShowAddPanel(!showAddPanel)}
                className="p-1.5 text-slate-500 hover:text-amber-600 hover:bg-amber-50 rounded-lg transition"
                title="Add files, repos, snippets"
              >
                <Plus className="h-4 w-4" />
              </button>
            </div>

            {/* Add File Form */}
            {showAddPanel && (
              <div className="p-4 border-b border-slate-100 bg-slate-50 space-y-3">
                {/* Browse files from system */}
                <div className="flex items-center gap-3 pb-3 border-b border-slate-200">
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    onChange={handleBrowseFiles}
                    className="hidden"
                    accept="*/*"
                  />
                  <button
                    onClick={() => fileInputRef.current?.click()}
                    className="flex items-center gap-2 px-4 py-2 bg-amber-600 text-white text-xs rounded-lg font-medium hover:bg-amber-700 transition"
                  >
                    <Upload className="h-3.5 w-3.5" />
                    Browse Files
                  </button>
                  <span className="text-[11px] text-slate-500">Select from your system</span>
                </div>

                <p className="text-[11px] text-slate-500 font-medium uppercase tracking-wide">Or add manually:</p>
                <div className="flex gap-2">
                  {(["file", "repo", "snippet"] as const).map((type) => (
                    <button
                      key={type}
                      onClick={() => setNewFileType(type)}
                      className={`px-3 py-1.5 text-xs rounded-lg font-medium transition flex items-center gap-1 ${
                        newFileType === type
                          ? "bg-amber-100 text-amber-700 border border-amber-300"
                          : "bg-white text-slate-600 border border-slate-200 hover:border-amber-300"
                      }`}
                    >
                      {type === "file" && <FileText className="h-3 w-3" />}
                      {type === "repo" && <FolderGit2 className="h-3 w-3" />}
                      {type === "snippet" && <FileCode className="h-3 w-3" />}
                      {type.charAt(0).toUpperCase() + type.slice(1)}
                    </button>
                  ))}
                </div>
                <input
                  type="text"
                  value={newFileName}
                  onChange={(e) => setNewFileName(e.target.value)}
                  placeholder={
                    newFileType === "file"
                      ? "File path (e.g., src/utils/auth.ts)"
                      : newFileType === "repo"
                        ? "Repo URL or owner/repo"
                        : "Snippet name"
                  }
                  className="w-full p-2 border border-slate-300 rounded-lg text-xs focus:ring-2 focus:ring-amber-500"
                />
                <textarea
                  value={newFileContent}
                  onChange={(e) => setNewFileContent(e.target.value)}
                  placeholder="Paste file content, code snippet, or repo description here..."
                  className="w-full h-28 p-2 border border-slate-300 rounded-lg text-xs font-mono focus:ring-2 focus:ring-amber-500 resize-none"
                />
                <div className="flex gap-2">
                  <button
                    onClick={handleAddFile}
                    disabled={!newFileName.trim() || !newFileContent.trim()}
                    className="px-3 py-1.5 bg-amber-600 text-white text-xs rounded-lg font-medium hover:bg-amber-700 disabled:bg-slate-300 transition"
                  >
                    Add Context
                  </button>
                  <button
                    onClick={() => setShowAddPanel(false)}
                    className="px-3 py-1.5 bg-slate-200 text-slate-600 text-xs rounded-lg font-medium hover:bg-slate-300 transition"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}

            {/* File List */}
            <div className="p-3 space-y-2 max-h-64 overflow-y-auto">
              {attachedFiles.length === 0 ? (
                <div className="text-center py-6 text-slate-400">
                  <Paperclip className="h-8 w-8 mx-auto mb-2 opacity-50" />
                  <p className="text-xs">No files attached</p>
                  <p className="text-[10px] mt-1">Add files, repos, or code snippets for context</p>
                </div>
              ) : (
                attachedFiles.map((file) => (
                  <div
                    key={file.id}
                    className="flex items-center justify-between p-2 bg-slate-50 rounded-lg border border-slate-100 group"
                  >
                    <div className="flex items-center gap-2 min-w-0">
                      {file.type === "file" && <FileText className="h-3.5 w-3.5 text-blue-500 shrink-0" />}
                      {file.type === "repo" && <FolderGit2 className="h-3.5 w-3.5 text-green-500 shrink-0" />}
                      {file.type === "snippet" && <FileCode className="h-3.5 w-3.5 text-purple-500 shrink-0" />}
                      <div className="min-w-0">
                        <p className="text-xs font-medium text-slate-700 truncate">{file.name}</p>
                        <p className="text-[10px] text-slate-400">{file.content.length} chars</p>
                      </div>
                    </div>
                    <button
                      onClick={() => handleRemoveFile(file.id)}
                      className="p-1 text-slate-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition"
                    >
                      <X className="h-3.5 w-3.5" />
                    </button>
                  </div>
                ))
              )}
            </div>
          </div>

          {/* Generated Files List */}
          {generatedFiles.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm">
              <div className="p-4 border-b border-slate-100">
                <h3 className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                  <FileCode className="h-4 w-4 text-green-500" />
                  Generated Files ({generatedFiles.length})
                </h3>
              </div>
              <div className="p-3 space-y-2 max-h-48 overflow-y-auto">
                {generatedFiles.map((file, idx) => (
                  <div key={idx} className="p-2 bg-green-50 rounded-lg border border-green-100">
                    <p className="text-xs font-medium text-slate-700 truncate">{file.file_path}</p>
                    <p className="text-[10px] text-slate-500 mt-0.5">
                      {file.language} &bull; {file.tokens} tokens &bull; {file.model}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Quick Build Templates */}
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm">
            <div className="p-4 border-b border-slate-100">
              <h3 className="text-sm font-semibold text-slate-700">Quick Templates</h3>
            </div>
            <div className="p-3 space-y-1.5">
              {[
                "Create a REST API endpoint with CRUD operations",
                "Build a React component with state management",
                "Write unit tests with mocking",
                "Create a database migration script",
                "Build a CI/CD pipeline (GitHub Actions)",
                "Create auth middleware with JWT",
              ].map((template) => (
                <button
                  key={template}
                  onClick={() => setPlanStep(template)}
                  className="w-full text-left text-xs p-2 bg-slate-50 border border-slate-100 rounded-lg hover:border-amber-300 hover:bg-amber-50 transition text-slate-600 hover:text-amber-700"
                >
                  {template}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
