"""WorkItem SDLC status enums (canonical P0)."""

from __future__ import annotations

# Forward path
STATUS_NEW = "NEW"
STATUS_INGESTED = "INGESTED"
STATUS_ANALYZED = "ANALYZED"
STATUS_PLANNED = "PLANNED"
STATUS_PLAN_APPROVED = "PLAN_APPROVED"
STATUS_EXECUTING = "EXECUTING"
STATUS_IMPLEMENTED = "IMPLEMENTED"
STATUS_VERIFYING = "VERIFYING"
STATUS_REVIEWING = "REVIEWING"
STATUS_ACCEPTANCE_TESTING = "ACCEPTANCE_TESTING"
STATUS_READY_TO_SHIP = "READY_TO_SHIP"
STATUS_SHIP_APPROVED = "SHIP_APPROVED"
STATUS_PR_CREATED = "PR_CREATED"
STATUS_CI_GREEN = "CI_GREEN"
STATUS_DONE = "DONE"

# Side statuses
STATUS_BLOCKED = "BLOCKED"
STATUS_FAILED_VERIFICATION = "FAILED_VERIFICATION"
STATUS_NEEDS_HUMAN_DECISION = "NEEDS_HUMAN_DECISION"
STATUS_CANCELLED = "CANCELLED"

SDLC_FORWARD = (
    STATUS_NEW,
    STATUS_INGESTED,
    STATUS_ANALYZED,
    STATUS_PLANNED,
    STATUS_PLAN_APPROVED,
    STATUS_EXECUTING,
    STATUS_IMPLEMENTED,
    STATUS_VERIFYING,
    STATUS_REVIEWING,
    STATUS_ACCEPTANCE_TESTING,
    STATUS_READY_TO_SHIP,
    STATUS_SHIP_APPROVED,
    STATUS_PR_CREATED,
    STATUS_CI_GREEN,
    STATUS_DONE,
)

SDLC_SIDE = (
    STATUS_BLOCKED,
    STATUS_FAILED_VERIFICATION,
    STATUS_NEEDS_HUMAN_DECISION,
    STATUS_CANCELLED,
)

ALL_STATUSES = set(SDLC_FORWARD) | set(SDLC_SIDE)

# Only EvidenceVerifier / orchestrator may set these from agent claims
GATE_STATUSES = frozenset({STATUS_READY_TO_SHIP, STATUS_DONE})
